name: Package and build alpha version

on:
  push:
    tags:
      - '**-alpha-**'
      - '**-beta-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取分支
        uses: actions/checkout@v1

      - name: 创建包
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}