name: Package and build release version

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '!**-alpha-**'
      - '!**-beta-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取分支
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: 创建包
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}